import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Keletron App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>Privacy Policy</h3>
        <p>
          Privacy Policy for Keletron Tennis on Apple Store, we are committed to
          protecting the privacy of our users. This Privacy Policy explains how
          we collect, use, and disclose your personal information when you use
          our mobile application. By using our mobile application, you consent
          to the collection, use, and disclosure of your personal information as
          described in this Privacy Policy.
        </p>
        <p>Information We Collect</p>
        <p>
          We may collect the following information when you use our mobile
          application:
        </p>
        <ul>
          <li>
            Personal information, such as your name, email address, when you
            create an account with us or contact us for support
          </li>
        </ul>
        <h3>How We Use Your Information</h3>
        <h4>We may use your information for the following purposes:</h4>
        <ul>
          <li>
            To provide you with the services and features of our mobile
            application
          </li>
          <li>
            To personalize and improve your experience with our mobile
            application
          </li>
          <li>
            To communicate with you about our mobile application and respond to
            your inquiries and support requests
          </li>
          <li>To enforce our Terms of Service and other policies</li>
          <li>To comply with legal obligations</li>
        </ul>
        <h4>How We Share Your Information</h4>
        <p>
          We do not share any of your information with Third parties or for
          marketing purposes
        </p>
        <h4>Your Choices</h4>
        <p>
          In order to use our app it is mandatory to privide an email address
          just for verification purposes
        </p>
        <h4>Security</h4>
        <p>
          We take reasonable measures to protect your information from
          unauthorized access, use, or disclosure. However, no method of
          transmission over the internet or electronic storage is completely
          secure, and we cannot guarantee absolute security.
        </p>
        <h4>Changes to this Privacy Policy</h4>
        <p>
          We may update this Privacy Policy from time to time. If we make
          material changes to this Privacy Policy, we will notify you by email
          or by posting a notice in our mobile application prior to the change
          becoming effective. Your continued use of our mobile application after
          the effective date of any changes to this Privacy Policy constitutes
          your acceptance of the changes.
        </p>
        <h4>Contact Us</h4>
        <p>
          If you have any questions or concerns about this Privacy Policy or our
          practices regarding your personal information, please contact us at
          [antonios.papadopan@gmail.com].
        </p>
      </main>
    </>
  );
}
